/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreeholeRouteImport } from './routes/treehole'
import { Route as LightRouteImport } from './routes/light'
import { Route as CompanionRouteImport } from './routes/companion'
import { Route as IndexRouteImport } from './routes/index'

const TreeholeRoute = TreeholeRouteImport.update({
  id: '/treehole',
  path: '/treehole',
  getParentRoute: () => rootRouteImport,
} as any)
const LightRoute = LightRouteImport.update({
  id: '/light',
  path: '/light',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionRoute = CompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companion': typeof CompanionRoute
  '/light': typeof LightRoute
  '/treehole': typeof TreeholeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companion': typeof CompanionRoute
  '/light': typeof LightRoute
  '/treehole': typeof TreeholeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companion': typeof CompanionRoute
  '/light': typeof LightRoute
  '/treehole': typeof TreeholeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/companion' | '/light' | '/treehole'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/companion' | '/light' | '/treehole'
  id: '__root__' | '/' | '/companion' | '/light' | '/treehole'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanionRoute: typeof CompanionRoute
  LightRoute: typeof LightRoute
  TreeholeRoute: typeof TreeholeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treehole': {
      id: '/treehole'
      path: '/treehole'
      fullPath: '/treehole'
      preLoaderRoute: typeof TreeholeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/light': {
      id: '/light'
      path: '/light'
      fullPath: '/light'
      preLoaderRoute: typeof LightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companion': {
      id: '/companion'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof CompanionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanionRoute: CompanionRoute,
  LightRoute: LightRoute,
  TreeholeRoute: TreeholeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
