/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreeholeRouteImport } from './routes/treehole'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LightRouteImport } from './routes/light'
import { Route as CompanionRouteImport } from './routes/companion'
import { Route as IndexRouteImport } from './routes/index'

const TreeholeRoute = TreeholeRouteImport.update({
  id: '/treehole',
  path: '/treehole',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LightRoute = LightRouteImport.update({
  id: '/light',
  path: '/light',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionRoute = CompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companion': typeof CompanionRoute
  '/light': typeof LightRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/treehole': typeof TreeholeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companion': typeof CompanionRoute
  '/light': typeof LightRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/treehole': typeof TreeholeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companion': typeof CompanionRoute
  '/light': typeof LightRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/treehole': typeof TreeholeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companion'
    | '/light'
    | '/login'
    | '/register'
    | '/treehole'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/companion' | '/light' | '/login' | '/register' | '/treehole'
  id:
    | '__root__'
    | '/'
    | '/companion'
    | '/light'
    | '/login'
    | '/register'
    | '/treehole'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanionRoute: typeof CompanionRoute
  LightRoute: typeof LightRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TreeholeRoute: typeof TreeholeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treehole': {
      id: '/treehole'
      path: '/treehole'
      fullPath: '/treehole'
      preLoaderRoute: typeof TreeholeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/light': {
      id: '/light'
      path: '/light'
      fullPath: '/light'
      preLoaderRoute: typeof LightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companion': {
      id: '/companion'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof CompanionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanionRoute: CompanionRoute,
  LightRoute: LightRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TreeholeRoute: TreeholeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
